name: React.js Frontend CI

on:
  push:
    branches: [ "test", "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm i

    - name: Run lint
      run: npm run lint
      working-directory: ./quiz-app

    - name: Install prettier
      run: npm install --save-dev --save-exact prettier

    - name: Run prettier
      run: npm run prettier

    - name: Run tests
      run: npm test
      env:
        CI: true 

    - name: Build
      run: npm run build

  frontend-image:
    needs: frontend-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and push backend Docker image
      run: |
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/frontend-js
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-js    

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/${{ secrets.DOCKER_USERNAME }}/frontend-js'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
